# Generated by Django 2.2 on 2020-02-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_new', '0002_auto_20200220_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_student',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
