# Generated by Django 2.2 on 2020-02-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='dd',
            field=models.CharField(default='dd', max_length=20),
        ),
    ]
